name: ba-jiarui-liu
extra-source-files: []
dependencies:
  - base
  - split
  - QuickCheck
default-extensions:
  - DuplicateRecordFields
library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
tests:
  ba-jiarui-liu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-jiarui-liu
      - hspec
