name: term-tasks
extra-source-files: []
dependencies:
  - base
  - split
  - QuickCheck
default-extensions:
  - DuplicateRecordFields
  - OverloadedLabels
library:
  source-dirs: src
  exposed-modules:
    - TermTasks.Direct
    - TermTasks.Perturbed
    - TermTasks.Records
    - TermTasks.DataType
    - TermTasks.Parser
  dependencies:
    - extra
    - parsec
    - output-monad
  ghc-options:
    - -Wall
    - -Werror
tests:
  term-tasks-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - term-tasks
      - hspec
