name: ba-jiarui-liu
extra-source-files: []
dependencies:
  - base
library:
  source-dirs: src
  exposed-modules: []
  ghc-options:
    - -Wall
    - -Werror
executables:
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-jiarui-liu
tests:
  ba-jiarui-liu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-jiarui-liu
      - hspec
