name: term-tasks
extra-source-files: []
dependencies:
  - base
  - split
  - QuickCheck
default-extensions:
  - DuplicateRecordFields
  - OverloadedLabels
library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
tests:
  term-tasks-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - term-tasks
      - hspec
executables:
  CertainSignature:
    main: Main.hs
    source-dirs: app/CertainSignature
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - term-tasks

  RandomSignature:
    main: Main.hs
    source-dirs: app/RandomSignature
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - term-tasks

  direct:
    main: direct.hs
    source-dirs: app/Autotool
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - term-tasks
    - extra

  perturbed:
    main: perturbed.hs
    source-dirs: app/Autotool
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - term-tasks
    - extra
