name: ba-jiarui-liu
extra-source-files: []
dependencies:
  - base
  - split
  - QuickCheck
default-extensions:
  - DuplicateRecordFields
  - OverloadedLabels
library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
tests:
  ba-jiarui-liu-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-jiarui-liu
      - hspec
executables:
  CertainSignature:
    main: Main.hs
    source-dirs: app/CertainSignature
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ba-jiarui-liu

  RandomSignature:
    main: Main.hs
    source-dirs: app/RandomSignature
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ba-jiarui-liu
