name: ba-ma-template
extra-source-files: []
dependencies:
  - base
library:
  source-dirs: src
  exposed-modules: []
  ghc-options:
    - -Wall
    - -Werror
executables:
  default:
    main: default.hs
    source-dirs: app
    dependencies:
      - ba-ma-template
tests:
  ba-ma-template-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ba-ma-template
      - hspec
