---
name: term-tasks
extra-source-files: []
dependencies:
  - base
  - containers
  - split
  - QuickCheck
  - extra
  - parsec
  - output-blocks >= 0.2
  - mtl
default-extensions:
  - DuplicateRecordFields
  - OverloadedLabels
library:
  source-dirs: src
  exposed-modules:
    - TermTasks.ValidTerm
    - TermTasks.InvalidTerm
    - TermTasks.Direct
    - TermTasks.Perturbed
    - TermTasks.Records
    - TermTasks.DataType
    - TermTasks.Parser
  ghc-options:
    - -Wall
    - -Werror
tests:
  term-tasks-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - term-tasks
      - hspec

