---
resolver: lts-19.30
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/output-blocks.git
    commit: d67590cb2e1a72ed72437a8cfe2972b680405569
    subdirs:
      - output-blocks
  - git: https://git.uni-due.de/fmi/autotool-dev
    commit: 56e75cd74d44f81ae52baa3b886025bd4d158bbb
    subdirs:
      - base
      - data
      - reader
      - todoc
      - transport
      - util
