---
resolver: nightly-2025-10-07
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/flex-tasks.git
    commit: e6d1d24ff5d3eddcfbbdc76c1e4de66169c2a405
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/output-blocks.git
    commit: d67590cb2e1a72ed72437a8cfe2972b680405569
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: c9ea223a41c1852d5e5d7ba35bc4f746c3edb634
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - git: https://git.uni-due.de/fmi/autotool-dev
    commit: 56e75cd74d44f81ae52baa3b886025bd4d158bbb
    subdirs:
      - base
      - data
      - reader
      - todoc
      - transport
      - util
  - diagrams-graphviz-1.4.1.1
  - latex-svg-image-0.2

allow-newer: true
