---
name: haskell-template-setup
version: 0.1.0.0

extra-source-files:
  - README.md
  - ChangeLog.md
synopsis: A task type setup for haskell template tasks of the e-learning platform Autotool
category: E-Learning
description: Please see the README on GitHub at <https://github.com/marcellussiegburg/haskell-template-setup#readme>
dependencies:
  - autotool-capabilities
  - autotool-capabilities-io-instances
  - base >= 4.7 && < 5
  - flex-tasks
  - output-blocks
  - parsec
  - string-interpolate
  - syb
  - term-tasks
  - yesod-form
library:
  source-dirs: .
