name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        plan:
          - { build: stack }

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install ${{ matrix.os }} Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: ${{ matrix.apt-get }}
        brew: ${{ matrix.brew }}
    - uses: actions/checkout@v2

    - name: Cache Stack
      id: cache-stack-unix
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}

    - name: Setup stack
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-no-global: true

    - name: Install dependencies
      run: |
        set -ex
        stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
        BUILD: ${{ matrix.plan.build }}

    - name: Build and test
      run: |
        set -ex
        stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
        BUILD: ${{ matrix.plan.build }}
        CABALVER: ${{ matrix.plan.cabal-install }}
